### ISSUE TITLE
Dulwich error when creating commits

### ISSUE THREAD

**Issue by J-DannyMartinez** [tickelton/impost0r#1]
Hi,
After reading over the readme, it seems the application errors out on the creating commit phase. Hopefully, this report can assist in improving the product!

**Environment**
* Ubuntu 20.04
* Python 3.8.5
* Dulwich 0.20.21

**Problem**
During the creation of commits, the application crashes with error: 
![image](https://user-images.githubusercontent.com/14081018/117182402-28b5e200-ad8b-11eb-818c-658d5d739d07.png)

**Attempted Troubleshooting**
* Reinstalling Dulwich
* Downgrading Dulwich to version 0.20.6
* Attempting to copy a different number of commits, from a user with 5 commits to >500

**Comment by tickelton** [comment]
On Ubuntu 20.04 with Python 3.8.5 I can not reproduce this error.
I tried Dulwich 0.20.21 and 0.20.6. Both seem to work fine.

I did run into a problem because Github now uses 'main' instead of 'master as the default branch name for new
repositories and I fixed that just now, but that doesn't seem to have anything to do with  your problem.

Unfortunately I can not see the cause of the error from your screenshot.
Can you please try it again with debug output like this and attach the output as a text file:

> ./impost0r.py -v -v -v

Please note that this will produce a lot of output!
The result should look approximately like the example output I attached here.
[impost0r.txt](https://github.com/tickelton/impost0r/files/6429229/impost0r.txt)

**Comment by J-DannyMartinez** [comment]
It always gets tougher when the issue is not reproduceable.
Here's my log on a new attempt with the same error: 
[log.txt](https://github.com/tickelton/impost0r/files/6429501/log.txt)


Additionally, I also attempted running the windows .exe on my Win10 machine, however the application seems to hang after entering my email - the image below has been the status for ~10 minutes now
![image](https://user-images.githubusercontent.com/14081018/117192877-12158800-ad97-11eb-9a0c-53658eed9944.png)

**Comment by tickelton** [comment]
I still can't reproduce it, but it looks like the URL string gets garbled and it's trying to connect to an invalid host.

Can you tell me which version of urllib3 you have installed ?

**Comment by J-DannyMartinez** [comment]
I am using urllib3 v.1.25.8!

**Comment by tickelton** [comment]
This might be a long shot, but it could have something to do with special characters in you password (if you have any).

You could try creating an access token as described here:
https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
and use that with impost0r.

That's probably a good idea in any case since Github will disable passwords for push access in the near future.

Please let me know if that changes anything.

**Comment by J-DannyMartinez** [comment]
Looks like that's making progress! 

After setting up an access token with all permissions enabled (for now, to ensure there are no permissions concerns) I no longer receive the original error, however, now it seems I am receiving a new error regarding porcelain in impost0r. Do you have any thoughts? Error is located at the end of the new log file:
[log2.txt](https://github.com/tickelton/impost0r/files/6437516/log2.txt)

```
Traceback (most recent call last):
  File "impost0r.py", line 317, in <module>
    main()
  File "impost0r.py", line 306, in main
    porcelain.push(repo_tmpdir, push_url, 'master', outstream=err_stream, errstream=err_stream)
  File "/usr/local/lib/python3.8/dist-packages/dulwich/porcelain.py", line 1102, in push
    result = client.send_pack(
  File "/usr/local/lib/python3.8/dist-packages/dulwich/client.py", line 1981, in send_pack
    new_refs = update_refs(dict(old_refs))
  File "/usr/local/lib/python3.8/dist-packages/dulwich/porcelain.py", line 1081, in update_refs
    selected_refs.extend(parse_reftuples(r.refs, refs, refspecs, force=force))
  File "/usr/local/lib/python3.8/dist-packages/dulwich/objectspec.py", line 143, in parse_reftuples
    ret.append(parse_reftuple(lh_container, rh_container, refspec, force=force))
  File "/usr/local/lib/python3.8/dist-packages/dulwich/objectspec.py", line 110, in parse_reftuple
    lh = parse_ref(lh_container, lh)
  File "/usr/local/lib/python3.8/dist-packages/dulwich/objectspec.py", line 85, in parse_ref
    raise KeyError(refspec)
KeyError: b'master'
```

**Comment by J-DannyMartinez** [comment]
Scratch that, digging into the impost0r file, I switched out "master" references" to main, in order to align with Github as you mentioned earlier. After that, the app completed successfully with no errors. Thank you for your assistance in this error!

**Comment by J-DannyMartinez** [comment]
May I ask that this issue be removed/deleted? I have mistakenly created it on the account I was planning to use impost0r on, and would prefer to keep this private if possible.
